### ISSUE TITLE
Don't start pipes with functions

### ISSUE THREAD

**Issue by tomekowal** [vruizext/phoenix1.4-json-rpc#1]
https://github.com/vruizext/phoenix1.4-json-rpc/blob/8c7e0eae1472cc00fb633a3c73ef02e8cec45dff/lib/json_rpc_api_web/controllers/json_rpc_controller.ex#L8

Style guides check if pipe chains start with raw values.
It would be good to change it to:

```
response =
  rpc_request
  |> parse(rpc_request)
  |> dispatch
```

**Comment by szymon-jez** [comment]
[And add parentheses `()` when calling functions](https://github.com/christopheradams/elixir_style_guide#parentheses-pipe-operator).
 
```elixir
response =
  rpc_request
  |> parse()
  |> dispatch()
```
